---
title: "임상시험자료분석II 프로젝트"
subtitle: 
  "의료기기의 임상시험 - PADS 데이터를 중심으로"
author: "신인수 (2023021390)"
date: "2024-12-13"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. 탐구동기

한 학기동안 임상시험 자료분석을 배우면서, 임상의약품에 대한 다양한 분석법과 사례들을 볼 수 있었다. 그러나 임상시험은 의약품에 국한되지 않고, 수술법, 의료기기 등에도 적용될 수 있다. 필자는 특히 의료기기(medical device)에 대한 임상시험이 어떻게 이루어지는지 궁금했고, 이를 프로젝트 주제로 삼고자 하였다.

프로젝트의 목표는 크게 두 가지이다. 우선 다양한 문헌을 참고하여 의료기기의 임상시험이 어떻게 이루어지는지, 의약품의 임상시험 어떤 방식과 차이가 있는지 탐구하는 것이다. 두 번째로는 파킨슨병 스마트워치 데이터셋 (Parkinson's Disease Smartwatch Dataset; PADS)을 바탕으로 스마트워치가 파킨슨병의 진단에 도움이 되는지 탐구하는 것이다.

# 2. 의료기기에 대한 임상시험

# 3. 데이터 소개

본 프로젝트에 사용된 데이터는 파킨슨 병 스마트워치 데이터셋(Parkinson's Disease Smartwatch Dataset; PADS)이다. 데이터에 대한 대략적인 정보와 출처는 다음과 같다.

- ClinicalTrials.gov ID: NCT03638479
- Physionet: https://physionet.org/content/parkinsons-disease-smartwatch/1.0.0/
- Kaggle: https://www.kaggle.com/datasets/eren2222/pads-parkinsons-disease-smartwatch-v1-0-0
- Gitlab: https://imigitlab.uni-muenster.de/published/pads-project

ClinicalTrials.gov에 등록된 임상시험이며, 프로토콜, 중간연구, 결과에 대한 논문은 각각 다음과 같다.

- Varghese, Julian, et al. "A smart device system to identify new phenotypical characteristics in movement disorders." Frontiers in neurology 10 (2019): 48.
- Varghese, Julian, et al. "Sensor validation and diagnostic potential of smartwatches in movement disorders." Sensors 21.9 (2021): 3139.
- Varghese, Julian, et al. "Machine Learning in the Parkinson’s disease smartwatch (PADS) dataset." npj Parkinson's Disease 10.1 (2024): 9.

이 데이터는 크게 환자 데이터, 설문조사 데이터와 스마트워치 데이터로 구성되어 있다. 

환자 데이터는 각 환자의 각 정보들로 구성되어 있는데, 다음과 같은 변수들로 구성되어 있다.

- `id`: 시험자 ID
- `condition`: 
  - Healthy (HC: Healthy Control)
  - Parkinson's (PD: Parkinson's Disease)
  - Differential Diagnosis; DD
    - Other Movement Disorders
    - Atypical Parkinsonism
    - Multiple Sclerosis
    - Essential Tremor
- `age_at_diagnosis`: 파킨슨병을 진단받은 나이
- `age`: 임상시험에 참여 시작할 때의 나이
- `height`: 신장
- `weight`: 체중
- `gender`: 성별
- `handedness`: 오른손잡이/왼손잡이
- `appearance_in_kinship`: 가족력
- `appearance_in_first_grade_kinship`: 가족력이 직계가족인지 여부
- `effect_of_alcohol_on_tremor`: 음주력이 떨림(tremor)의 영향을 주는지 - "Unknown"     "No effect", "Worsening", "Improvement"
- `label`: 반응변수 - 0: HC, 1:PD, 2:DD

설문조사 데이터는 International Parkinson and Movement Disorder Society로부터 개발된 PDNMS (Parkinson's Disease non-motor symptom) 설문지 데이터이다. 총 30문항으로 구성되며, Yes/No로 답변할 수 있다. 설문조사지는 발표자료에 첨부하도록 하겠다. 건강한 시험자는 모두 No로 대답하기 때문에, Yes로 답한 문항이 많을수록 심각한 증세를 가지고 있다고 생각할 수 있다. 또한, 30개 문항은 10가지 항목으로 구분된다. 분류 항목과 해당되는 문제 번호는 다음과 같다. 

- Gastrointestinal tract: 1, 3, 4, 5, 6, 7
- Urinal tract 8, 9
- Pain: 10
- Miscellaneous: 11, 28, 29
- Apathy/Attention/Memory: 12, 13, 15
- Distortion of perception: 2, 14, 30
- Depression/Anxiety: 16, 17
- Sexual Function: 18, 19
- Cardiovascular: 20, 21, 27
- Sleep/Fatigue : 22, 23, 24, 25, 26

스마트워치 데이터는 시험자에게 10분동안, 10초 또는 20초 간격으로 지정된 동작을 지시한 후, 스마트워치로부터 수집한 가속도 센서(Accelerometer)와 중력센서(Gyroscope)의 데이터이다. 지정된 동작은 11개이며, 각 시험자는 왼쪽과 오른쪽 손목에 스마트워치를 차기 때문에, 각 환자당 10분동안 측정된 22개의 시계열 데이터가 측정된다. 그리고 각 시계열 데이터는 6개의 신호로 구성되는데, 가속도 센터의 X, Y, Z 축 측정값, 중력 센서의 X, Y, Z 축 측정값에 해당된다. 마찬가지로 시험 동작에 대한 정보는 발표자료에 첨부하도록 하겠다.

# 4. 데이터 전처리

## 4.1 기존 전처리 방법
논문에서는 다음과 같은 4가지 방법으로 파생변수를 만든 뒤에 머신러닝, 딥러닝 방법으로 분석한다.

1. 수동적으로 정의된 파생변수
2. Symbolic Fourier Approximation (SFA)를 기반으로 한 Bag-of-SFA-Symbols (BOSS) 알고리즘으로 파생변수 생성
3. 딥러닝 기반 XceptionTime을 기반으로 파생변수 생성
4. 설문조사 데이터 이용.

본 탐구에서는 1번과 4번 방법을 이용하여 데이터 전처리를 한 후, 수업 시간에 배운 자료분석 방법을 바탕으로 추가적인 분석을 할 것이다. 

1번에서 정의된 파생변수는 네 가지이다. 

1. Welch 방법을 이용한 전력 스펙트럼 밀도(power spectral density; PSD)
2. 각 시계열을 4등분한 후 표준편차(standard deviation), 절대 최대 진폭(maximum absolute amplitude), 절대 에너지 합(sum of absolute energy).

이 파생변수를 바탕으로 본래 연구에서는 머신러닝/딥러닝 방법을 이용하여 환자군을 분류하였다.

각 변수에 대한 공식은 다음과 같다

| **Variable**                | **Equation**                                                        |
|-----------------------------|---------------------------------------------------------------------|
| Power Spectral Density (PSD)| $$PSD(f) = \frac{1}{K} \sum_{i=1}^{K} |X_i(f)|^2$$                  |
| Standard Deviation          | $$\sigma = \sqrt{\frac{1}{N} \sum_{i=1}^{N} (x_i - \mu)^2}$$        |
| Maximum Absolute Amplitude  | $$\text{Max Absolute Amplitude} = \max(|x_1|, |x_2|, \dots, |x_N|)$$|
| Sum of Absolute Energy      | $$\text{Sum of Absolute Energy} = \sum_{i=1}^{N} |x_i|$$            |

## 4.2 탐구에 이용한 전처리 방법

본 탐구에서는 전처리를 다음과 같이 하였다. 

1. 각 시계열 데이터에서 구간을 나누지 않고 PSD, 표준편차, 절대 최대 진폭, 절대 에너지 총합을 구한 후 총합을 구한다. 
2. 설문조사는 점수 총합, 10개 항목 부분점수를 이용한다.
3. `age_of_diagnosis`과 `age`의 차이를 `duration`으로 계산. 파킨슨 병 진행 햇수를 의미.
4. 227번 환자의 신장이 55cm로, 오타로 추정. 155cm로 수정

# 5. 데이터 분석

데이터 분석은 크게 네 종류를 진행할 예정이다. 첫 번째는 데이터에 대한 탐색적 자료분석이다. 두 번째는 설문조사에 대한 카이제곱 검정이다. 세 번째는 HC, PD, DD 세 집단에 대한 ANOVA 분석이다. 마지막으로 HC를 기준으로 하는 다항 로지스틱 회귀분석(Multinomial logistic regression)을 진행한다.

## 5.1 탐색적 자료분석 (EDA)

우선 건강한 사람(1번 환자)과 파킨슨 병 환자 (6번 환자)에 대한 시계열 그림의 차이를 보도록 하자.


## 5.2 설문조사에 대한 카이제곱 검정

## 5.3 집단별 분석 (ANOVA)

## 5.4 다항 로지스틱 회귀분석 (Multinomial logistic regression)

# 6. 결론

# 7. 참고문헌

- Varghese, Julian, et al. "A smart device system to identify new phenotypical characteristics in movement disorders." Frontiers in neurology 10 (2019): 48.
- Varghese, Julian, et al. "Sensor validation and diagnostic potential of smartwatches in movement disorders." Sensors 21.9 (2021): 3139.
- Varghese, Julian, et al. "Machine Learning in the Parkinson’s disease smartwatch (PADS) dataset." npj Parkinson's Disease 10.1 (2024): 9.
- Chaudhuri, Kallol Ray, et al. "International multicenter pilot study of the first comprehensive self‐completed nonmotor symptoms questionnaire for Parkinson's disease: the NMSQuest study." Movement disorders: official journal of the Movement Disorder Society 21.7 (2006): 916-923.
